services:
    funddy.jsrouting.controller.jsroutingcontroller:
        class: Funddy\Bundle\JsRoutingBundle\Controller\JsRoutingController
        arguments:
            - @funddy.jsrouting.service.jsroutesexporter