php:
    - 5.3
    - 5.4

node_js:
    - 0.8
    - 0.6

before_script:
    - ROOT_DIR=`pwd`
    - NODE_ROOT_DIR=$ROOT_DIR/Resources/public/js
    - sudo apt-get install php5-cli phpunit php-pear nodejs npm
    - sudo pear channel-discover pear.phpunit.de
    - sudo pear channel-discover components.ez.no
    - sudo pear channel-discover pear.symfony-project.com
    - sudo pear install --alldeps phpunit/PHPUnit
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install
    - cd $NODE_ROOT_DIR && npm install
    - cd $ROOT_DIR

script: phpunit && cd $NODE_ROOT_DIR && make test
